#!/bin/bash

if [ `uname -s` == "Linux" ]; then
  mknod -m 660 /dev/ram0 b 1 0
  mknod -m 660 /dev/ram1 b 1 1
fi

cat /etc/hosts
ls -la /dev
df -k /dev
export PATH=/opt/chef/embedded/bin:$PATH
cd /opt/chef/embedded/apps/chef

/opt/chef/embedded/bin/bundle install
/opt/chef/embedded/bin/bundle exec /opt/chef/embedded/bin/rspec --format progress
