#!/bin/bash

# setup /dev/ram* on linux
if [ `uname -s` == "Linux" ]; then
  mknod -m 660 /dev/ram0 b 1 0
  mknod -m 660 /dev/ram1 b 1 1
fi

# remove ip6 entries for docker
egrep -v "ip6" > /etc/hosts.new
cat /etc/hosts.new > /etc/hosts

cat /etc/hosts
ls -la /dev
df -k /dev
export PATH=/opt/chef/embedded/bin:$PATH
cd /opt/chef/embedded/apps/chef

/opt/chef/embedded/bin/bundle install
/opt/chef/embedded/bin/bundle exec /opt/chef/embedded/bin/rspec --format progress
