#!/bin/bash

cat /etc/hosts
ls -la /dev
df -k /dev
export PATH=/opt/chef/embedded/bin:$PATH
cd /opt/chef/embedded/apps/chef

/opt/chef/embedded/bin/bundle install
/opt/chef/embedded/bin/bundle exec /opt/chef/embedded/bin/rspec --format progress
