language: ruby
cache: bundler
dist: trusty

# Early warning system to catch if Rubygems breaks something
before_install:
  - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
  - gem --version
    # travis may preinstall a bundler gem which is later than the one which we pin, which may totally hose us, so we preemtively
    # uninstall anything they may have installed here.  if they haven't installed anything then we have to ignore the failure
    # to uninstall the default bundler that ships embedded in ruby itself.
  - rvm @global do gem uninstall bundler -a -x || true
  - gem install bundler -v $(grep :bundler omnibus_overrides.rb | cut -d'"' -f2)
  - bundle --version
  - rm -f .bundle/config
  - gem uninstall rspec -v 3.8.0

before_script:
 # force all .rspec tests into progress display to reduce line count
 - echo --color > .rspec
 - echo -fp >> .rspec
 # necessary for sudo: true tests, ingore failures on tests invoked with sudo: false
 - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers

# do not run expensive spec tests on PRs, only on branches
branches:
  only:
  - master
  - chef-14
  - chef-13

env:
  global:
    - FORCE_FFI_YAJL=ext

matrix:
  include:
  - rvm: 2.4.4
    services: docker
    sudo: required
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep :bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test rspec-centos-7
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - CENTOS=7
      - KITCHEN_YAML=kitchen.travis.yml

notifications:
  on_change: true
  on_failure: true
  on_success: change
  on_pull_requests: false
